/**
 * Common disposable/temporary email domains.
 * Used to block referral fraud via throwaway accounts.
 */
export const DISPOSABLE_EMAIL_DOMAINS = new Set(
  [
    // Popular temporary email services
    'tempmail.com',
    'temp-mail.org',
    'temp-mail.io',
    'tempmailo.com',
    'tempinbox.com',
    'guerrillamail.com',
    'guerrillamail.net',
    'guerrillamail.org',
    'guerrillamail.de',
    'guerrillamailblock.com',
    'grr.la',
    'sharklasers.com',
    'guerrillamail.info',
    'mailinator.com',
    'mailinator2.com',
    'mailinator.net',
    'maildrop.cc',
    'maildrop.gq',
    '10minutemail.com',
    '10minutemail.net',
    '10mail.org',
    'minutemail.com',
    'dispostable.com',
    'disposableemailaddresses.emailmiser.com',
    'yopmail.com',
    'yopmail.fr',
    'yopmail.gq',
    'yopmail.net',
    'throwaway.email',
    'throwaway.me',
    'trashmail.com',
    'trashmail.net',
    'trashmail.me',
    'trashmail.org',
    'trashmail.de',
    'fakeinbox.com',
    'fakemail.net',
    'mailnesia.com',
    'mailnull.com',
    'mailsac.com',
    'mailslurp.com',
    'mohmal.com',
    'getnada.com',
    'nada.ltd',
    'emailondeck.com',
    'emailfake.com',
    'crazymailing.com',
    'tempr.email',
    'tempail.com',
    'discard.email',
    'discardmail.com',
    'discardmail.de',
    'harakirimail.com',
    'mailcatch.com',
    'meltmail.com',
    'spamgourmet.com',
    'spambox.us',
    'mytemp.email',
    'burnermail.io',
    'inboxkitten.com',
    'tmpmail.net',
    'tmpmail.org',
    'tempmailaddress.com',
    'getairmail.com',
    'mailforspam.com',
    'safetymail.info',
    'filzmail.com',
    'anonymbox.com',
    'emailtemporario.com.br',
    'emkei.cz',
    'jetable.org',
    'incognitomail.com',
    'mailexpire.com',
    'mailzilla.com',
    'spamfree24.org',
    'tempomail.fr',
    'wegwerfmail.de',
    'wegwerfmail.net',
    'einrot.com',
    'e4ward.com',
    'mintemail.com',
    'mt2015.com',
    'thankyou2010.com',
    'trash-mail.at',
  ]
    .filter(Boolean)
    .map((d) => d.toLowerCase()),
);

/**
 * Check if an email address uses a disposable domain.
 */
export function isDisposableEmail(email: string): boolean {
  const domain = email.split('@')[1]?.toLowerCase();
  if (!domain) return false;
  return DISPOSABLE_EMAIL_DOMAINS.has(domain);
}
