export const POINTS_PAGE_COPY = {
  en: {
    weekdays: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    referralEmailBonus: 'Referral email verification bonus',
    transactionActions: {
      registration: 'New user registration bonus',
      email_verification: 'Email verification bonus',
      referred_registration: 'Referral registration bonus',
      referral_email_verification: 'Referral email verification bonus',
      complete_profile: 'Profile completion bonus',
      first_favorite: 'First intent action bonus',
      first_share: 'First share bonus',
      daily_browse_5_products: 'Daily browse reward',
      daily_favorite_product: 'Daily favorite reward',
      share_product: 'Product share reward',
      daily_checkin: 'Daily check-in',
      referral_conversion: 'Referral conversion reward',
    },
    transactionDescriptions: {
      'New user registration bonus': 'New user registration bonus',
      'Email verification bonus': 'Email verification bonus',
      'Referral registration bonus': 'Referral registration bonus',
      'Referral email verification bonus': 'Referral email verification bonus',
      'Profile completion bonus': 'Profile completion bonus',
      'First favorite bonus': 'First intent action bonus',
      'First intent action bonus': 'First intent action bonus',
      'First share bonus': 'First share bonus',
      'Product share reward': 'Product share reward',
      'Daily check-in': 'Daily check-in',
    },
    milestonePrefix: 'Milestone bonus:',
    pointsExpiredSuffix: 'points expired',
  },
  zh: {
    weekdays: ['日', '一', '二', '三', '四', '五', '六'],
    referralEmailBonus: '推荐用户邮箱验证奖励',
    transactionActions: {
      registration: '新用户注册奖励',
      email_verification: '邮箱验证奖励',
      referred_registration: '推荐注册奖励',
      referral_email_verification: '推荐用户邮箱验证奖励',
      complete_profile: '完善资料奖励',
      first_favorite: '首次高意图动作奖励',
      first_share: '首次分享奖励',
      daily_browse_5_products: '每日浏览奖励',
      daily_favorite_product: '每日收藏奖励',
      share_product: '商品分享奖励',
      daily_checkin: '每日签到',
      referral_conversion: '推荐转化奖励',
    },
    transactionDescriptions: {
      'New user registration bonus': '新用户注册奖励',
      'Email verification bonus': '邮箱验证奖励',
      'Referral registration bonus': '推荐注册奖励',
      'Referral email verification bonus': '推荐用户邮箱验证奖励',
      'Profile completion bonus': '完善资料奖励',
      'First favorite bonus': '首次高意图动作奖励',
      'First intent action bonus': '首次高意图动作奖励',
      'First share bonus': '首次分享奖励',
      'Daily browse 5 products reward': '每日浏览 5 个商品奖励',
      'Daily favorite product reward': '每日收藏商品奖励',
      'Product share reward': '商品分享奖励',
      'Daily check-in': '每日签到',
    },
    milestonePrefix: '阶段奖励：',
    pointsExpiredSuffix: '积分已过期',
  },
  fr: {
    weekdays: ['Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
    referralEmailBonus: "Bonus de vérification d'e-mail du parrainage",
    transactionActions: {
      registration: "Bonus d'inscription d'un nouvel utilisateur",
      referred_registration: "Bonus d'inscription par parrainage",
      referral_email_verification:
        "Bonus de vérification d'e-mail du parrainage",
      complete_profile: 'Bonus de profil complété',
      first_favorite: "Bonus de première action d'intention",
      first_share: 'Bonus premier partage',
      share_product: 'Récompense de partage de produit',
      daily_checkin: 'Check-in quotidien',
      referral_conversion: 'Récompense de conversion de parrainage',
    },
    transactionDescriptions: {
      'New user registration bonus':
        "Bonus d'inscription d'un nouvel utilisateur",
      'Referral registration bonus': "Bonus d'inscription par parrainage",
      'Referral email verification bonus':
        "Bonus de vérification d'e-mail du parrainage",
      'Profile completion bonus': 'Bonus de profil complété',
      'First favorite bonus': "Bonus de première action d'intention",
      'First intent action bonus': "Bonus de première action d'intention",
      'First share bonus': 'Bonus premier partage',
      'Product share reward': 'Récompense de partage de produit',
      'Daily check-in': 'Check-in quotidien',
    },
    milestonePrefix: 'Bonus de palier :',
    pointsExpiredSuffix: 'points expirés',
  },
  de: {
    weekdays: ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
    referralEmailBonus: 'Bonus für Referral-E-Mail-Verifizierung',
    transactionActions: {
      registration: 'Neuer Nutzer Registrierungsbonus',
      referred_registration: 'Empfehlungs-Registrierungsbonus',
      referral_email_verification: 'Bonus für Referral-E-Mail-Verifizierung',
      complete_profile: 'Bonus für vollständiges Profil',
      first_favorite: 'Bonus für erste Absichtsaktion',
      first_share: 'Bonus für erstes Teilen',
      share_product: 'Belohnung für Produktfreigabe',
      daily_checkin: 'Täglicher Check-in',
      referral_conversion: 'Belohnung für Referral-Konvertierung',
    },
    transactionDescriptions: {
      'New user registration bonus': 'Neuer Nutzer Registrierungsbonus',
      'Referral registration bonus': 'Empfehlungs-Registrierungsbonus',
      'Referral email verification bonus':
        'Bonus für Referral-E-Mail-Verifizierung',
      'Profile completion bonus': 'Bonus für vollständiges Profil',
      'First favorite bonus': 'Bonus für erste Absichtsaktion',
      'First intent action bonus': 'Bonus für erste Absichtsaktion',
      'First share bonus': 'Bonus für erstes Teilen',
      'Product share reward': 'Belohnung für Produktfreigabe',
      'Daily check-in': 'Täglicher Check-in',
    },
    milestonePrefix: 'Meilenstein-Bonus:',
    pointsExpiredSuffix: 'Punkte verfallen',
  },
  es: {
    weekdays: ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'],
    referralEmailBonus: 'Bono de verificación de correo por referido',
    transactionActions: {
      registration: 'Bono de registro de nuevo usuario',
      referred_registration: 'Bono de registro por referido',
      referral_email_verification: 'Bono de verificación de correo por referido',
      complete_profile: 'Bono por completar el perfil',
      first_favorite: 'Bono por primera acción de intención',
      first_share: 'Bono por primera vez compartido',
      share_product: 'Recompensa por compartir producto',
      daily_checkin: 'Check-in diario',
      referral_conversion: 'Recompensa por conversión de referido',
    },
    transactionDescriptions: {
      'New user registration bonus': 'Bono de registro de nuevo usuario',
      'Referral registration bonus': 'Bono de registro por referido',
      'Referral email verification bonus':
        'Bono de verificación de correo por referido',
      'Profile completion bonus': 'Bono por completar el perfil',
      'First favorite bonus': 'Bono por primera acción de intención',
      'First intent action bonus': 'Bono por primera acción de intención',
      'First share bonus': 'Bono por primera vez compartido',
      'Product share reward': 'Recompensa por compartir producto',
      'Daily check-in': 'Check-in diario',
    },
    milestonePrefix: 'Bono por hito:',
    pointsExpiredSuffix: 'puntos vencidos',
  },
  it: {
    weekdays: ['Dom', 'Lun', 'Mar', 'Mer', 'Gio', 'Ven', 'Sab'],
    referralEmailBonus: 'Bonus verifica email referral',
    transactionActions: {
      registration: 'Bonus registrazione nuovo utente',
      referred_registration: 'Bonus registrazione referral',
      referral_email_verification: 'Bonus verifica email referral',
      complete_profile: 'Bonus profilo completato',
      first_favorite: 'Bonus prima azione di intenzione',
      first_share: 'Bonus prima condivisione',
      share_product: 'Ricompensa condivisione prodotto',
      daily_checkin: 'Check-in giornaliero',
      referral_conversion: 'Ricompensa conversione referral',
    },
    transactionDescriptions: {
      'New user registration bonus': 'Bonus registrazione nuovo utente',
      'Referral registration bonus': 'Bonus registrazione referral',
      'Referral email verification bonus': 'Bonus verifica email referral',
      'Profile completion bonus': 'Bonus profilo completato',
      'First favorite bonus': 'Bonus prima azione di intenzione',
      'First intent action bonus': 'Bonus prima azione di intenzione',
      'First share bonus': 'Bonus prima condivisione',
      'Product share reward': 'Ricompensa condivisione prodotto',
      'Daily check-in': 'Check-in giornaliero',
    },
    milestonePrefix: 'Bonus traguardo:',
    pointsExpiredSuffix: 'punti scaduti',
  },
  pt: {
    weekdays: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
    referralEmailBonus: 'Bônus de verificação de e-mail por indicação',
    transactionActions: {
      registration: 'Bônus de cadastro de novo usuário',
      referred_registration: 'Bônus de cadastro por indicação',
      referral_email_verification:
        'Bônus de verificação de e-mail por indicação',
      complete_profile: 'Bônus por completar perfil',
      first_favorite: 'Bônus da primeira ação de intenção',
      first_share: 'Bônus do primeiro compartilhamento',
      share_product: 'Recompensa por compartilhar produto',
      daily_checkin: 'Check-in diário',
      referral_conversion: 'Recompensa por conversão de indicação',
    },
    transactionDescriptions: {
      'New user registration bonus': 'Bônus de cadastro de novo usuário',
      'Referral registration bonus': 'Bônus de cadastro por indicação',
      'Referral email verification bonus':
        'Bônus de verificação de e-mail por indicação',
      'Profile completion bonus': 'Bônus por completar perfil',
      'First favorite bonus': 'Bônus da primeira ação de intenção',
      'First intent action bonus': 'Bônus da primeira ação de intenção',
      'First share bonus': 'Bônus do primeiro compartilhamento',
      'Product share reward': 'Recompensa por compartilhar produto',
      'Daily check-in': 'Check-in diário',
    },
    milestonePrefix: 'Bônus de marco:',
    pointsExpiredSuffix: 'pontos expirados',
  },
  ar: {
    weekdays: ['الأحد', 'الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت'],
    referralEmailBonus: 'مكافأة التحقق من البريد الإلكتروني للإحالة',
    transactionActions: {
      registration: 'مكافأة تسجيل مستخدم جديد',
      referred_registration: 'مكافأة التسجيل عبر الإحالة',
      referral_email_verification: 'مكافأة التحقق من البريد الإلكتروني للإحالة',
      complete_profile: 'مكافأة إكمال الملف الشخصي',
      first_favorite: 'مكافأة أول إجراء نية',
      first_share: 'مكافأة أول مشاركة',
      share_product: 'مكافأة مشاركة المنتج',
      daily_checkin: 'تسجيل يومي',
      referral_conversion: 'مكافأة تحويل الإحالة',
    },
    transactionDescriptions: {
      'New user registration bonus': 'مكافأة تسجيل مستخدم جديد',
      'Referral registration bonus': 'مكافأة التسجيل عبر الإحالة',
      'Referral email verification bonus':
        'مكافأة التحقق من البريد الإلكتروني للإحالة',
      'Profile completion bonus': 'مكافأة إكمال الملف الشخصي',
      'First favorite bonus': 'مكافأة أول إجراء نية',
      'First intent action bonus': 'مكافأة أول إجراء نية',
      'First share bonus': 'مكافأة أول مشاركة',
      'Product share reward': 'مكافأة مشاركة المنتج',
      'Daily check-in': 'تسجيل يومي',
    },
    milestonePrefix: 'مكافأة المرحلة:',
    pointsExpiredSuffix: 'نقطة منتهية الصلاحية',
  },
} as const;

export type PointsPageCopy =
  (typeof POINTS_PAGE_COPY)[keyof typeof POINTS_PAGE_COPY];

export function getPointsPageCopy(locale: string): PointsPageCopy {
  return (
    POINTS_PAGE_COPY[locale as keyof typeof POINTS_PAGE_COPY] ??
    POINTS_PAGE_COPY.en
  );
}
